version: '3'
services:
  sonerezh-db:
    image: mariadb
    volumes:
      - sonerezh-db-data:/var/lib/mysql
    env_file: 
      - mariadb.env
      - database-info.env
    restart: always
  app:
    image: sonerezh/sonerezh:latest
    depends_on:
      - sonerezh-db
    volumes:
      - /path/to/your/music:/music:ro
      - sonerezh-thumnails:/thumbnails
    links:
      - sonerezh-db:sonerezh-db
    ports:
      - 8080:80
    env_file:
      - database-info.env
    restart: always
volumes:
  sonerezh-db-data:
    driver: local
  sonerezh-thumnails:
    driver: local